name: Shellcheck and tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bc

      - name: Check
        run: ./check
        env:
          SHLIB_REQUIRE_SHELLCHECK: "1"

      - name: Check for failures
        if: ${{ failure() }}
        uses: https://github.com/ivan-ristovic/action-gitea-workflow-error-email@v1
        with:
          smtp-host: ${{ secrets.SMTP_HOST }}
          smtp-username: ${{ secrets.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.SMTP_FROM }}
          to: ${{ secrets.WORKFLOW_ERROR_EMAIL }}


